spring:
  application:
    name: message
  mvc:
    servlet:
      path: /message # localhost:8085/message

server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

